name: "fahcsim.grafana_stack.prometheus"
on:
  push:
    paths:
      - 'roles/prometheus/**'
      - 'molecule/prometheus/**'
      - '.github/workflows/prometheus.yml'
  pull_request:
    paths:
      - 'roles/prometheus/**'
      - 'molecule/prometheus/**'
      - '.github/workflows/prometheus.yml'
jobs:
  molecule:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        distro:
          - ubuntu2204
          - debian11
        collection_role:
          - prometheus
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/fahcsim/grafana_stack

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] yamllint ansible-lint
      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_DISTRO=${{ matrix.distro }}
          molecule --debug test -s prometheus
